const experienceData = [
  {
    company: "Paycom",
    role: "Software Developer (Full-time)",
    location: "Texas, USA",
    duration: "June 2025 – Present",
    latest: true,
    skills: ["PHP", "ReactJS", "MySQL", "ASP.NET", "GitLab"],
    highlights: [
      "Develop and implement new system features to enhance functionality and improve user experience within Paycom’s enterprise platform.",
      "Diagnose, debug, and resolve software issues and performance bottlenecks while addressing security vulnerabilities to maintain system reliability and integrity.",
      "Design and execute comprehensive test cases to validate functionality of cross-team development projects, ensuring seamless integration and bug-free deployment.",
    ],
  },
  {
    company: "UNT",
    role: "Research Assistant (Part-time)",
    location: "Texas, USA",
    duration: "Jan 2024 – May 2025",
    latest: false,
    skills: ["Material Science", "Python", "Machine Learning"],
    highlights: [
      "Engaged in material science research, analyzing stress, strain, and hardening rate in alloys, focusing on advanced curve path predictions.",
      "Developed Python code to calculate 5 key parameter values from stress-strain curves of high entropy alloys stored in a database for future research.",
      "Contributed to developing machine learning algorithms to predict chemical compositions based on 100+ parameter values, achieving an accuracy of 85%.",
    ],
  },
  {
    company: "UNT",
    role: "Teaching Assistant – ML and AI (Part-time)",
    location: "Texas, USA",
    duration: "Aug 2024 – May 2025",
    latest: false,
    skills: [
      "Machine Learning",
      "Artificial Intelligence",
      "Python",
      "Teaching",
      "Mentoring",
    ],
    highlights: [
      "Assisted in delivering a graduate-level Machine Learning and AI course to 120+ students, grading 100+ assignments and providing feedback.",
      "Conducted office hours and mentoring sessions, addressing queries from students weekly.",
      "Managed course logistics by maintaining detailed grades and attendance records with 100% accuracy.",
    ],
  },
  {
    company: "Paycom",
    role: "Software Development Intern (Internship)",
    location: "Texas, USA",
    duration: "May 2024 – Aug 2024",
    latest: false,
    skills: ["ReactJS", "C#", "ASP.NET", "MySQL", "OOP", "SOLID", "Scrum"],
    highlights: [
      "Developed and maintained full-stack web applications using React, C#, ASP.NET, and MySQL.",
      "Utilized Swagger for efficient API testing and documentation.",
      "Contributed to Scrum teams, managing project changes, identifying and resolving project issues.",
    ],
  },
  {
    company: "UNT",
    role: "Software Interface Developer (Part-time)",
    location: "Texas, USA",
    duration: "Nov 2023 – Dec 2023",
    latest: false,
    skills: ["Angular", "Web Development", "UI/UX"],
    highlights: [
      "Led development of a user-friendly Angular website for Prof. Sanjukta Bhowmick, boosting efficiency by 20%.",
      "Made ongoing improvements to ensure responsive and smooth website performance.",
    ],
  },
  {
    company: "LTIMindtree",
    role: "Software Engineer (Full-time)",
    location: "Hyderabad, India",
    duration: "Sep 2022 – Jul 2023",
    latest: false,
    skills: ["Spring Boot", "Angular", "MySQL", "Web Development", "Agile"],
    highlights: [
      "Developed and maintained responsive web applications using Spring Boot, Angular, and MySQL.",
      "Collaborated with cross-functional teams to improve usability and optimize performance.",
      "Conducted unit tests, code reviews, and participated in agile development processes.",
    ],
  },
  {
    company: "Mindtree",
    role: "Java Developer (Internship)",
    location: "Hyderabad, India",
    duration: "Mar 2022 – Jun 2022",
    latest: false,
    skills: ["Java", "Spring Boot", "Angular", "MySQL", "HTML", "CSS", "Agile"],
    highlights: [
      "Used agile methodology for a 98% on-time delivery rate and 30% productivity increase for a hospital management project.",
      "Conducted unit testing and debugging, resulting in a 98% bug-free codebase.",
    ],
  },
  {
    company: "Samarth IT Solutions",
    role: "Web Developer (Internship)",
    location: "Hyderabad, India",
    duration: "May 2021 – Aug 2021",
    latest: false,
    skills: ["HTML", "CSS", "MySQL", "ReactJS", "Full-Stack Development"],
    highlights: [
      "Built a To-do web app, increasing skills by 80%.",
      "Gained full-stack development proficiency with HTML, CSS, MySQL, and ReactJS, improving productivity by 60%.",
    ],
  },
  {
    company: "University of North Texas",
    role: "Web Developer – Dynamic Graph Research Project",
    location: "USA",
    duration: "Nov 2024 – May 2025",
    latest: false,
    skills: ["ReactJS", "Web Development", "Data Visualization"],
    highlights: [
      "Designed and developed an interactive React-based website to visualize and analyze dynamic graph research.",
      "Enhanced usability and real-time data interpretation.",
    ],
  },
  {
    company: "Baptist Church",
    role: "Web Developer (Freelancing)",
    location: "Hyderabad, India",
    duration: "May 2022 – Jul 2022",
    latest: false,
    skills: ["ReactJS", "Bootstrap", "CSS", "Web Development"],
    highlights: [
      "Created a ReactJS website for a church with a 95% client satisfaction rate.",
      "Used Bootstrap and CSS for an appealing layout and optimized load times under 1 second.",
    ],
  },
];

export default experienceData;
